version: "3"

volumes:
  node_modules:
services:
  nuxt-app-test:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
  cypress:
    image: "cypress/included:13.6.2"
    depends_on:
      nuxt-app-test:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://nuxt-app-test:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
